// <auto-generated />
using System;
using CompenseAgora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompenseAgora.Data.Migrations
{
    [DbContext(typeof(CompenseAgoraDbContext))]
    [Migration("20260824224250_AddCognitoAuthToPessoa")]
    partial class AddCognitoAuthToPessoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompenseAgora.Entities.Combustivel", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int?>("CodigoCombustivelBiogenico")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoCombustivelFossil")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCombustivelBiogenico");

                    b.HasIndex("CodigoCombustivelFossil");

                    b.ToTable("COMBUSTIVEL", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.ConsumoMedioFrota", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("CodigoFrota")
                        .HasColumnType("int");

                    b.Property<decimal>("Consumo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("ParaTodos")
                        .HasColumnType("bit");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoFrota");

                    b.ToTable("CONSUMO_MEDIO_FROTA", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.Energia", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CodigoPessoa")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CriadoEm")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("date");

                    b.Property<decimal>("EmissaoCO2")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoPessoa");

                    b.ToTable("ENERGIA", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.FatorCombustivel", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("CH4")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CO2")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("CodigoCombustivel")
                        .HasColumnType("int");

                    b.Property<decimal>("Densidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("N2O")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PoderCalorificoInferior")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCombustivel");

                    b.ToTable("FATORES_DO_COMBUSTIVEL", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.FatorComposicaoCombustivel", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualBiodiesel")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PercentualEtanol")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Codigo");

                    b.ToTable("FATOR_COMPOSICAO_COMBUSTIVEL", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.FatorEnergia", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("FeSin")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("FATOR_ENERGIA", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.Frota", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int?>("CodigoCombustivelBiogenico")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoCombustivelFossil")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCombustivelPrimario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCombustivelBiogenico");

                    b.HasIndex("CodigoCombustivelFossil");

                    b.HasIndex("CodigoCombustivelPrimario");

                    b.ToTable("FROTA", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.GasEfeitoEstufa", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("GWP")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Codigo");

                    b.ToTable("GAS_EFEITO_ESTUFA", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.Pessoa", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CognitoSub")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Codigo");

                    b.HasIndex("CognitoSub")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PESSOA", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.Viagem", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("AnoFrota")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCombustivel")
                        .HasColumnType("int");

                    b.Property<int>("CodigoFrota")
                        .HasColumnType("int");

                    b.Property<int>("CodigoPessoa")
                        .HasColumnType("int");

                    b.Property<decimal>("Consumo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("CriadoEm")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("date");

                    b.Property<decimal>("DistanciaKM")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("EmissaoCO2")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCombustivel");

                    b.HasIndex("CodigoFrota");

                    b.HasIndex("CodigoPessoa");

                    b.ToTable("VIAGEM", (string)null);
                });

            modelBuilder.Entity("CompenseAgora.Entities.Combustivel", b =>
                {
                    b.HasOne("CompenseAgora.Entities.Combustivel", "CombustivelBiogenico")
                        .WithMany()
                        .HasForeignKey("CodigoCombustivelBiogenico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CompenseAgora.Entities.Combustivel", "CombustivelFossil")
                        .WithMany()
                        .HasForeignKey("CodigoCombustivelFossil")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CombustivelBiogenico");

                    b.Navigation("CombustivelFossil");
                });

            modelBuilder.Entity("CompenseAgora.Entities.ConsumoMedioFrota", b =>
                {
                    b.HasOne("CompenseAgora.Entities.Frota", "Frota")
                        .WithMany("ConsumosMedios")
                        .HasForeignKey("CodigoFrota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Frota");
                });

            modelBuilder.Entity("CompenseAgora.Entities.Energia", b =>
                {
                    b.HasOne("CompenseAgora.Entities.Pessoa", "Pessoa")
                        .WithMany("Energias")
                        .HasForeignKey("CodigoPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("CompenseAgora.Entities.FatorCombustivel", b =>
                {
                    b.HasOne("CompenseAgora.Entities.Combustivel", "Combustivel")
                        .WithMany("FatoresDoCombustivel")
                        .HasForeignKey("CodigoCombustivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combustivel");
                });

            modelBuilder.Entity("CompenseAgora.Entities.Frota", b =>
                {
                    b.HasOne("CompenseAgora.Entities.Combustivel", "CombustivelBiogenico")
                        .WithMany("FrotasComoBiogenico")
                        .HasForeignKey("CodigoCombustivelBiogenico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CompenseAgora.Entities.Combustivel", "CombustivelFossil")
                        .WithMany("FrotasComoFossil")
                        .HasForeignKey("CodigoCombustivelFossil")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CompenseAgora.Entities.Combustivel", "CombustivelPrimario")
                        .WithMany("FrotasComoPrimario")
                        .HasForeignKey("CodigoCombustivelPrimario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CombustivelBiogenico");

                    b.Navigation("CombustivelFossil");

                    b.Navigation("CombustivelPrimario");
                });

            modelBuilder.Entity("CompenseAgora.Entities.Viagem", b =>
                {
                    b.HasOne("CompenseAgora.Entities.Combustivel", "Combustivel")
                        .WithMany("Viagens")
                        .HasForeignKey("CodigoCombustivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompenseAgora.Entities.Frota", "Frota")
                        .WithMany("Viagens")
                        .HasForeignKey("CodigoFrota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompenseAgora.Entities.Pessoa", "Pessoa")
                        .WithMany("Viagens")
                        .HasForeignKey("CodigoPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combustivel");

                    b.Navigation("Frota");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("CompenseAgora.Entities.Combustivel", b =>
                {
                    b.Navigation("FatoresDoCombustivel");

                    b.Navigation("FrotasComoBiogenico");

                    b.Navigation("FrotasComoFossil");

                    b.Navigation("FrotasComoPrimario");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("CompenseAgora.Entities.Frota", b =>
                {
                    b.Navigation("ConsumosMedios");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("CompenseAgora.Entities.Pessoa", b =>
                {
                    b.Navigation("Energias");

                    b.Navigation("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
